### ISSUE TITLE
Reading / writing bug.

### ISSUE THREAD

**Issue by vlad4ernyshov** [lolo-io/OneList#12]
Hello!
First of all, I want to thank you for this application. This is the best, easiest, most convenient that I found! Please do not stop.

In the process of running the application, I get errors related to reading / writing to the media. I recorded a video: https://youtu.be/Q70WQPdUt8o
Xiaomi Mi MAX 3.

**Comment by lolo-io** [comment]
Hello,
Thank you for the report, I will work on it, I don't know yet how to reproduce it.

Is "Test" a list you just created or imported ? And is it stored in app private storage (Shared Preferences) or extrernal path ?

**Comment by lolo-io** [comment]
I think I found the origin of the bug.
The URI permission isn'nt kept after the device is rebooted. I wil work on a fix soon.

**Comment by lolo-io** [comment]
The errors occurs when uing the "Default Storage Folder" in the settings.
Somehow the permission isn't properly granted on some devices.

A temporary workaround would be to save each list you want to export by chosing the path from the list options: 
Long click a list -> edit -> more options -> click the floppy and set your path from here.

That seems to work event after reboots.

**Comment by lolo-io** [comment]
I have fixed the issue.

Once you have the app updated, in order to fix it on your side, you'll have to go to the setings and set again the default file path, 
You'll have to set again the path on the lists that are still buggy.

The permissions were not properly granted, but now they will, after you set the path again.

Please tell me if this works well for you.

**Comment by vlad4ernyshov** [comment]
Hello,
I apologize for the delay in responding. I followed your instructions and now everything works fine. Thank you so much for such a quick update!
