### ISSUE TITLE
Make the function "Undo" after deleting the list item.

### ISSUE THREAD

**Issue by vlad4ernyshov** [lolo-io/OneList#16]
Sometimes I accidentally delete lines with a swipe. Is it possible to restore the last deleted note?
Thank you!

**Comment by vlad4ernyshov** [comment]
[https://alternativeto.net/software/1list/](url)

**Comment by newhinton** [comment]
#20

**Comment by sphh** [comment]
I would really love to have this feature! I inadvertently deleted an important item from the list and now it's gone forever :(

**Comment by msjoberg** [comment]
The same here, and often it goes so quickly (with the swipe left action) you are unsure what you just deleted. +1 for having undo or confirmation for deleting item.

**Comment by lolo-io** [comment]
I will implement this when I have some time (hopefully within this month). @newhinton  has already made some work on it #20 . 
Didn't implemented it yet because some work is still to do.

**Comment by lolo-io** [comment]
Implemented.
