### ISSUE TITLE
Default storage folder is ignored

### ISSUE THREAD

**Issue by stumpelrilz** [lolo-io/OneList#26]
I want to set the "Default storage folder" to "/storage/emulated/0" because then I can access the file(s) for making a backup of it.

But the app ignores this and stores the settings and my lists always here:
/data/data/com.lolo.io.onelist/shared_prefs/MainActivity.xml

**Comment by estearg** [comment]
Same issue here.
Thank you for the app.

**Comment by lolo-io** [comment]
Should be fixed, or different with [4abc6f5](https://github.com/lolo-io/OneList/commit/4abc6f5eacd50868ea693a2b64a5538d5f65f27d)
