### ISSUE TITLE
Please let the order of the list-items as they are

### ISSUE THREAD

**Issue by stumpelrilz** [lolo-io/OneList#27]
When clicking on a list-item to mark it as done I would prefer the following behavior:
The item ist moved down into the "done" area, but in the same position as it was before clicking.

When cliking again on it, it should appear in the same position as in the beginning.

Reason:
When making a shopping list for a specific shop, I often buy the same things (e.g. bread, etc.).
Therefore the list is ordered in the same order as they are appearing when I walk through the shop.
In the current situation I have to re-order the list every time before I go shopping.

If this is not possible, the list-items could be just left in its place and just marked as "done".
Making this configurable is probably preferable.

**Comment by lolo-io** [comment]
I will work on an option to choose weteher the striked items go to the end or stay where they are

**Comment by lolo-io** [comment]
Same issue as #10
