### ISSUE TITLE
[Feature Request] Localization Platforms

### ISSUE THREAD

**Issue by RickyM7** [lolo-io/OneList#35]
It would be great if your project were added to some localization platform, such as [Hosted WebLate](https://hosted.weblate.org/hosting/) or [POEditor](https://poeditor.com/). These platforms have free plans and make the work of translators much easier.

**Comment by lolo-io** [comment]
Hi, I don't think this is a priority as the app doesn't have a large amount of strings.

**Comment by RickyM7** [comment]
Got it!
