### ISSUE TITLE
Allow User To Change Colors In App

### ISSUE THREAD

**Issue by landry314** [lolo-io/OneList#36]
I'd like to be able to configure the color highlights in the app.

This could be accomplished either by adding a setting with a color wheel or by expanding the 'Theme' Settings to be more than Dark or Light like 'Dark Red', 'Dark Green', Dark Blue', 'Light Orange' for example...

Would be nice, right?

**Comment by lolo-io** [comment]
Hi, I don't think this is a priority right now. App main color is red and that's what makes its identity.
