### ISSUE TITLE
Bullet

### ISSUE THREAD

**Issue by sphh** [lolo-io/OneList#37]
Working on a small (tiny!) screen, the bullet takes up scarce space and does not convey any information at all:
- It does not change, if the item is deleted.
- It has no function, like the "expand" caret
- It is positioned in the wrong place: I would expect it aligned with the first line and not in the middle of the item, which makes it hard to figure out, where an item starts.

May I suggest to remove the bullet and either
- colour the items' background alternating (white/very light grey) for the light theme, or
- put a horizontal line between the individual items.

Thanks.

**Comment by lolo-io** [comment]
I like those bullets 😂. Maybe placing them at the top of the item is a good idea 👍.
I can consider hiding the bullets for small screens only and implement one of the two suggestions.

The reason I don't want to implement them on large screen is that I want to keep a "minimalist" approach with OneList and adding full width lines and backgrounds would over overload the screen, in my opinion.

**Comment by sphh** [comment]
Here is another idea for small screens: Since the bullet has only a visible function (and you cannot tick or untick it), give it the functionality of the expand caret (and remove that from the right-hand side), so the bullet would:
- show a bullet, if there is nothing to expand
- show the closed caret, if there is a comment available, but it is not shown
- show the open caret, if the comment is shown.

You keep the bullet but still gain space. No alternating background or horizontal lines needed!

**Comment by lolo-io** [comment]
Nice, I ma okay with this. I will work on it as soon as I have free time to do so.

**Comment by sphh** [comment]
Great, thank.

When you do it, could you please also look at #33, which – frankly – is the a show stopper for this app …

**Comment by lolo-io** [comment]
I will !

**Comment by lolo-io** [comment]
Should be fixed with 1d234a0
