### ISSUE TITLE
Import/export for backup/sharing

### ISSUE THREAD

**Issue by Arnaudv6** [lolo-io/OneList#4]
Hey @lolo-io, great app !  
I am recommending it to all my relatives !  
I'd like to see two things added one day: 
first is import/export feature, where we could select lists to include.  
No need to go down to item level for inclusion.  

I'll fill a second report with my second idea.

**Comment by Arnaudv6** [comment]
Wrong title sorry

**Comment by Arnaudv6** [comment]
Thinking back on that one, maybe that could take the form of a "share via" button ? Not sure.

**Comment by lolo-io** [comment]
Hi @Arnaudv6 , thank you for your ideas ! I am currently thinking of adding the choice to save the lists on the public internal storage, which will be as if it was exported, and also allow the users to sync their lists with their other devices by saving the file on dropbox for instance (and will require an import button too).
Share via is also a good feature to add.

**Comment by Arnaudv6** [comment]
Your solution is good to me, feel free to forget about "share via". Thanks for the reply

**Comment by lolo-io** [comment]
I've implemented the feature.
You can now select where your list are saved, and you can import them from an existing file.
I've implemented a share button too, but it shares the list as plain text, to send it vis text message for example.

**Comment by Arnaudv6** [comment]
Waiting for it to show in fdroid :-) but thannnnnks ! 👍
