### ISSUE TITLE
enhancement : store list on drive in ICS format + date + linked tasks

### ISSUE THREAD

**Issue by jlmxyz** [lolo-io/OneList#46]
Hi!
it would be great (and also really usefull for sync and display in other app) if the list could be saved in ICS format
a todo can then have :  

- a link to another task (start after, subtask)
- a deadline
- a start date (if linked "stat after" to another task, then start date is either the deadline or the date when the task is marked as completed
- extra field like task completion (if subtask the completion of main task is computed as sum of completion of all task)

since in ICS format, the list can be sinced to a web calendar and displayed on computer

thanks and regards

**Comment by lolo-io** [comment]
This is a minialistic list app. For more advanced feature you can use more advanced lists app that supports all this kind of features.
