### ISSUE TITLE
[feature] allow edit / reorder items / groups / subtasks

### ISSUE THREAD

**Issue by jlmxyz** [lolo-io/OneList#48]
I often misstype my item... it's too bad we can't edit them 

same for ordering, high priority on top, low on bottom, right now I manage to to this by marking them as done and undoo the marking... but this works only to make the item go up into the list...

subgrouping is also needed, when you have a "buy list" and you want to group them by location (supermarket, butcher....) 

and when a task is too big, it could be nice to be able to split it....

**Comment by lolo-io** [comment]
You can edit the item by swiping it left.
Custom ordering will be implemented one day https://github.com/lolo-io/OneList/issues/32
Subgoups wont be implemented.
Splitting a list won't be implemented.

This is a minimalistic ilst app. Lots of users like it for its simplicity. I won't add a lot of overwhelming features.
