### ISSUE TITLE
[feature] support ICS as task storage file and rfc9253 task relations

### ISSUE THREAD

**Issue by jlmxyz** [lolo-io/OneList#49]
it's long time that I would love to have a task app that use ICS file format and https://datatracker.ietf.org/doc/html/rfc9253 for creating a "project like" app (a litlle bit like ms project)
lot of tasks have relationships, they can't be started before another, should be started before the end of another... or just are composed of several tasks that have some relationship or have due dates...... that's too bad that even if the ICS permit such relations, there is no app that handle this and allow to take advantage of ics/webcal storage to share tasks....

**Comment by lolo-io** [comment]
I don't understand what you lean.
I won't add ICS support. this is not a task app, this is a minimalistic list app.
