### ISSUE TITLE
Time elapsed

### ISSUE THREAD

**Issue by Arnaudv6** [lolo-io/OneList#5]
Second idea here:
Give a rought time estimation for the last time each item got deactivated/checked-off.  
fuzzy time, really. Like so: https://octobanana.com/blog/programming-a-fuzzy-time-function 
This would allow for quick reminder: how long since I last changed my contact-lenses ?
Since I bought my last not-so-healthy-but-so-delicious cake ?
Or went visiting GrandMa ?

**Comment by lolo-io** [comment]
Why not, I will consider adding it in a future release.

**Comment by lolo-io** [comment]
This wont be added. The app is supposed to stay a simple and minimalist list app.

**Comment by Arnaudv6** [comment]
yes OK, good to see you're back :-)
