### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [lolo-io/OneList#51]
Since gradle 8 is used, we use jdk 17. But it seems it doesn't have javax so the build failed. See https://gitlab.com/linsui/fdroiddata/-/jobs/6039887550. Could you please take a look? Thanks!

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/6522298107 The build still fails.

**Comment by linsui** [comment]
Maybe you need to clean the cache.

**Comment by lolo-io** [comment]
I did. It still works well and it also works on the Github CI. 
I added `-dontwarn javax.annotation.**` and deleted / created a new tag
