### ISSUE TITLE
Error while getting your list from %s. Displaying cached one instead.

### ISSUE THREAD

**Issue by cjaone** [lolo-io/OneList#52]
Sometimes a file can't be loaded, then the cached version is used instead. Maybe it appeared first after an Android update many months ago, at least I can't remember observing the issue before. 

I looked at the file which can't be loaded. It ends with:

         "stableId":1698909616871}}}}

It has 4 '}', that's 3 too many.

**It looks as if writing the file does not delete the previous contents (if the previous file was bigger)**, instead it seems to just overwrite it without deleting the remaining characters (if the previous file was bigger).

Just tried to add another entry to the file and quit and opened 1List again: The error message disappeared. It seems the contents are ok now because the new file is bigger (so that it fully overwrites the previous file).

Android 14

**Comment by cjaone** [comment]
Steps to reproduce:

1. Add a new list
2. Add an entry to this list
3. Tap on it (so that it is "done")
4. Close the app
5. Open the app again

-> Error message appears.

**Comment by lolo-io** [comment]
This should be fixed now.
