### ISSUE TITLE
Cannot save lists on sd-card

### ISSUE THREAD

**Issue by accountForIssues** [lolo-io/OneList#7]
Great job with the app ! Really like the ability to export the lists.

However, I'm an unable to export the lists to my sdcard. Only the internal memory and the app private storage work. 

I just get a toast message saying "failed to save ...1list"

**Comment by lolo-io** [comment]
Hi ! thanks for noticing, I thought it worked but indeed it doednt on most devices. I'm working on it !

**Comment by lolo-io** [comment]
Hi ! I have implemented sd card support. It's available on version 1.2. :)
