### ISSUE TITLE
too easy to accidentally delete items in list

### ISSUE THREAD

**Issue by clach04** [lolo-io/OneList#75]
This is not recoverable from as there does not appear to be an undelete.

It's also tricky to discover the swipe left is delete behavior, the tutorial is excellent though!

Possibly options:
  * Long press brings up delete button on right hand side which can then be pressed

**Comment by the-loan-wolf** [comment]
Yes it's frustrating

**Comment by lolo-io** [comment]
There is now a way to undo the delete action by swiping the item right before it is fully deleted.
