### ISSUE TITLE
App update not published on FDroid

### ISSUE THREAD

**Issue by lolo-io** [lolo-io/OneList#87]
I published an update with a new tag 3 weeks ago. Normally updates with this tag prefix are automatically pushed on FDroid.

tag : onelist-1.5.0

@licaon-kter any idea why it's not working ?

**Comment by licaon-kter** [comment]
https://github.com/lolo-io/OneList/blob/onelist-1.5.0/app/build.gradle.kts#L29 I don't see a new version, F-Droid already has `19`

**Comment by lolo-io** [comment]
Thanks @licaon-kter , I updated the code, it should be alright now.

**Comment by licaon-kter** [comment]
Great, the checkupdate bot will pick it up soon™

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/com.lolo.io.onelist/20#site-footer The build failed.

**Comment by lolo-io** [comment]
@linsui  I don't understand what's the problem. Build passes on my CI and I haven't changed config since last update.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7771210545 The build failed.

**Comment by lolo-io** [comment]
This error is happening when running  `/home/vagrant/fdroidserver/gradlew-fdroid clean`.
There is no error when running `./gradlew clean` on this repo.

@linsui  @licaon-kter

**Comment by licaon-kter** [comment]
@lolo-io can you verify if your local gradle is 8.6 too?

ref: https://github.com/gradle/gradle/issues/18971

**Comment by lolo-io** [comment]
@licaon-kter yes I am running gradle 8.6.

https://github.com/lolo-io/OneList/blob/develop/gradle/wrapper/gradle-wrapper.properties

**Comment by linsui** [comment]
```
vagrant@bookworm:~/build/com.lolo.io.onelist$ ./gradlew clean assembleRelease
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.6/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
Type-safe project accessors is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'com.lolo.io.onelist' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
> Cannot generate project dependency accessors:
    - Cannot generate project dependency accessors because project 'com.lolo.io.onelist' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
```

I tried with gradlew but it still failed.

**Comment by linsui** [comment]
This can be fixed by added rootProject.name. It's not related to fdroid-gradlew at all. The name is the dir name of the repo. On the F-Droid buildserver the repo dir name is the app id. If it's a name without `.` it works. Gradle is really stupid. Such a stupid problem is not fixed for 2 years...

**Comment by lolo-io** [comment]
Thanks @licaon-kter for the help.
I've added `rootProject.name="com-lolo-io-onelist"` to `settings.gradle` (replaced the dots by dashes). Hopefully the build will pass this time 🤞

**Comment by linsui** [comment]
Thanks!
